### PR TITLE
Add an update-frontend goal for updating src/main/frontend based on add-ons

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/maven-plugin/98)

### CODE REVIEW

**Comment by elmot** [comment]
How about tests?

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java, line 93 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-KhbvBGyHVSwsNDZw9EF:-KhbvBGzsq0ii6WHhR3r:b6u1fdf) ([raw file](https://github.com/vaadin/maven-plugin/blob/11c53e90103828ae32627b688c5ee29c79d3660f/src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java#L93)):*
> ```Java
>         }
>         if (!currentBowerJsonDeps.equals(found)) {
>             getLog().info("Dependencies have been updated");
> ```

Its better have something done and then report.

---

*[src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java, line 147 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-KhbyIKmCJ6PTaDrcVD6:-KhbyIKmCJ6PTaDrcVD7:byyypam) ([raw file](https://github.com/vaadin/maven-plugin/blob/11c53e90103828ae32627b688c5ee29c79d3660f/src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java#L147)):*
> ```Java
>     }
> 
>     private void generateAddonBowerJson(LinkedHashMap<String, String> found)
> ```

What if the project had some addons with bower deps before, and then user remove one (or all of them) ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-:-KhbydUzNZI59CVLHZlH:b-eio6hm)*

**Comment by gilberto-torrezan** [comment]
Review status: 1 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java, line 46 at r2](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-Ki-o0-UhyH-0jce4jTb:-Ki-o0-UhyH-0jce4jTc:b-yalwu7) ([raw file](https://github.com/vaadin/maven-plugin/blob/174dfe4509702d0740a42cda0698b1edef3232ad/src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java#L46)):*
> ```Java
>  * <code>false</code> or <code>true</code> depending on whether the bower.json
>  * was updated or not. This property can be used together with e.g. a
>  * {@code skip} configuration of other plugins.
> ```

The official way the `maven-frontend-plugin` skips the bower process is by using the `skip.bower` property. Is it possible to reuse the same syntax?

---

*[src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java, line 54 at r2](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-Ki-nLGct4vYWVKcZ48r:-Ki-nLGct4vYWVKcZ48s:bnyxg3m) ([raw file](https://github.com/vaadin/maven-plugin/blob/174dfe4509702d0740a42cda0698b1edef3232ad/src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java#L54)):*
> ```Java
>     private static final String VAADIN_BOWER_OK_PROPERTY = "vaadin.bower.ok";
> 
>     private static final String FRONTEND_DIR = "src/main/frontend/";
> ```

This is a property that I feel should be configurable - the default is of course `src/main/frontend`.

---

*[src/main/resources/com/vaadin/integration/maven/move-build-to-webapp.js, line 8 at r2](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-Ki-mG9LtUB4sI1eAC5o:-Ki-mG9MWeasJeyr9Kud:b-fajgsp) ([raw file](https://github.com/vaadin/maven-plugin/blob/174dfe4509702d0740a42cda0698b1edef3232ad/src/main/resources/com/vaadin/integration/maven/move-build-to-webapp.js#L8)):*
> ```JavaScript
> const fs = require('fs');
> 
> const frontendVaadin = "../webapp/VAADIN/frontend";
> ```

Should this be "(something)/VAADIN/static/frontend" ?

On a second note: please make this output folder configurable somehow. Moving everything to `src/main/webapp` can make Eclipse crazy, for no real benefit (since the copied files are almost "binary" at this point).

---

*[src/main/resources/com/vaadin/integration/maven/polymer.json, line 12 at r2](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-Ki-lSc1qvsFRBEVFe4u:-Ki-lSc2VuCoZiuELhwL:bbfxpbf) ([raw file](https://github.com/vaadin/maven-plugin/blob/174dfe4509702d0740a42cda0698b1edef3232ad/src/main/resources/com/vaadin/integration/maven/polymer.json#L12)):*
> ```JSON
>     {
>       "name": "es5",
>       "bundle": true,
> ```

For Flow applications, is better not to bundle the resources (so they can be downloaded separately). Is it possible to make this option configurable at the plugin?

---

*[src/main/resources/com/vaadin/integration/maven/polymer.json, line 14 at r2](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-Ki-lnG8HBobTohJGtJ5:-Ki-lnG8HBobTohJGtJ6:b-3bgk06) ([raw file](https://github.com/vaadin/maven-plugin/blob/174dfe4509702d0740a42cda0698b1edef3232ad/src/main/resources/com/vaadin/integration/maven/polymer.json#L14)):*
> ```JSON
>       "bundle": true,
>       "js": {
>         "minify": true,
> ```

About minification: in development mode is interesting to be able to serve non-minified files. Is that possible to make it configurable at the plugin?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/98)*

**Comment by Artur-** [comment]
Review status: 1 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java, line 93 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-KhbvBGyHVSwsNDZw9EF:-Ki-tz-Z_lq-lkQ0D08B:b-896fix) ([raw file](https://github.com/vaadin/maven-plugin/blob/11c53e90103828ae32627b688c5ee29c79d3660f/src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java#L93)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

Its better have something done and then report.
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java, line 147 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-KhbyIKmCJ6PTaDrcVD6:-Ki-u3Ss5o6COCpI8KkF:b-9ur59f) ([raw file](https://github.com/vaadin/maven-plugin/blob/11c53e90103828ae32627b688c5ee29c79d3660f/src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java#L147)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

What if the project had some addons with bower deps before, and then user remove one (or all of them) ?
</blockquote></details>

This method only generates the `vaadin-addons/bower.json`. If you already have an existing `bower.json`, you need to add a dependency to this file

---

*[src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java, line 46 at r2](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-Ki-o0-UhyH-0jce4jTb:-Ki-oarxRVJBT5BrY_Nf:bql5oos) ([raw file](https://github.com/vaadin/maven-plugin/blob/174dfe4509702d0740a42cda0698b1edef3232ad/src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java#L46)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

The official way the `maven-frontend-plugin` skips the bower process is by using the `skip.bower` property. Is it possible to reuse the same syntax?
</blockquote></details>

The idea with using a different property is that we do not control the `maven-frontend-plugin` directly, but instead give the user the control so he can configure the project in any way they like. Maybe it's not useful and could be simplified to just set e.g. `skip.yarn` (want to skip the whole thing starting from `yarn`, not only `bower install`)

---

*[src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java, line 54 at r2](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-Ki-nLGct4vYWVKcZ48r:-Ki-rqunqR99UrSjzLTi:b-896fix) ([raw file](https://github.com/vaadin/maven-plugin/blob/174dfe4509702d0740a42cda0698b1edef3232ad/src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java#L54)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

This is a property that I feel should be configurable - the default is of course `src/main/frontend`.
</blockquote></details>

Done.

---

*[src/main/resources/com/vaadin/integration/maven/move-build-to-webapp.js, line 8 at r2](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-Ki-mG9LtUB4sI1eAC5o:-Ki-vQt5QzAvLZakmR75:b-1zeqbj) ([raw file](https://github.com/vaadin/maven-plugin/blob/174dfe4509702d0740a42cda0698b1edef3232ad/src/main/resources/com/vaadin/integration/maven/move-build-to-webapp.js#L8)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Should this be "(something)/VAADIN/static/frontend" ?

On a second note: please make this output folder configurable somehow. Moving everything to `src/main/webapp` can make Eclipse crazy, for no real benefit (since the copied files are almost "binary" at this point).
</blockquote></details>

Made it configurable - this default matches what is used in https://github.com/vaadin/framework/pull/9083 for the `frontend://` protocol. Not sure if this makes sense either for the same reasons as commented below

---

*[src/main/resources/com/vaadin/integration/maven/polymer.json, line 12 at r2](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-Ki-lSc1qvsFRBEVFe4u:-Ki-vmQS-CqDoI2wKsVA:b-dg8wr) ([raw file](https://github.com/vaadin/maven-plugin/blob/174dfe4509702d0740a42cda0698b1edef3232ad/src/main/resources/com/vaadin/integration/maven/polymer.json#L12)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

For Flow applications, is better not to bundle the resources (so they can be downloaded separately). Is it possible to make this option configurable at the plugin?
</blockquote></details>

Could, but let's not do all the things in this initial patch. I'm not 100% sure either how you would use the parameters in a sensible way for the files generated only once. It would have to be something like `mvn vaadin:update-frontend -Dbundle=false`, which would be quite strange if you previously ran `mvn vaadin:update-frontend` without any paramteter and your  `mvn vaadin:update-frontend -Dbundle=false` command would then result in a bundle being created (as these files are not overwritten ever)

---

*[src/main/resources/com/vaadin/integration/maven/polymer.json, line 14 at r2](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-Ki-lnG8HBobTohJGtJ5:-Ki-w06DJo83LTs29hwy:b-ya81ng) ([raw file](https://github.com/vaadin/maven-plugin/blob/174dfe4509702d0740a42cda0698b1edef3232ad/src/main/resources/com/vaadin/integration/maven/polymer.json#L14)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

About minification: in development mode is interesting to be able to serve non-minified files. Is that possible to make it configurable at the plugin?
</blockquote></details>

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/98)*

**Comment by gilberto-torrezan** [comment]
Review status: 1 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main/resources/com/vaadin/integration/maven/polymer.json, line 12 at r2](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-Ki-lSc1qvsFRBEVFe4u:-Ki0-IESyRkxuhIHYGYd:b-blvcku) ([raw file](https://github.com/vaadin/maven-plugin/blob/174dfe4509702d0740a42cda0698b1edef3232ad/src/main/resources/com/vaadin/integration/maven/polymer.json#L12)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

Could, but let's not do all the things in this initial patch. I'm not 100% sure either how you would use the parameters in a sensible way for the files generated only once. It would have to be something like `mvn vaadin:update-frontend -Dbundle=false`, which would be quite strange if you previously ran `mvn vaadin:update-frontend` without any paramteter and your  `mvn vaadin:update-frontend -Dbundle=false` command would then result in a bundle being created (as these files are not overwritten ever)
</blockquote></details>

That property could be set at the `pom.xml`, and described at the Flow Documentation as "mandatory configuration". So the developer wouldn't need to remember to send that flag every time.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/98)*

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 12 files at r1, 11 of 12 files at r2, 1 of 1 files at r3.
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/98)*

**Comment by Artur-** [comment]
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/resources/com/vaadin/integration/maven/polymer.json, line 12 at r2](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-Ki-lSc1qvsFRBEVFe4u:-Ki08r6qB4xMYP_VIoy-:bxttwmb) ([raw file](https://github.com/vaadin/maven-plugin/blob/174dfe4509702d0740a42cda0698b1edef3232ad/src/main/resources/com/vaadin/integration/maven/polymer.json#L12)):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

That property could be set at the `pom.xml`, and described at the Flow Documentation as "mandatory configuration". So the developer wouldn't need to remember to send that flag every time.
</blockquote></details>

Added options for minify and bundle

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/98)*

**Comment by elmot** [comment]
Reviewed 1 of 12 files at r1, 1 of 12 files at r2, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java, line 147 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-KhbyIKmCJ6PTaDrcVD6:-Ki08YXLu58B0hkI6N3n:bm2gl8p) ([raw file](https://github.com/vaadin/maven-plugin/blob/11c53e90103828ae32627b688c5ee29c79d3660f/src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java#L147)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary><blockquote>

This method only generates the `vaadin-addons/bower.json`. If you already have an existing `bower.json`, you need to add a dependency to this file
</blockquote></details>

What if I _remove_ a dependency, is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/98)*

**Comment by elmot** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java, line 147 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-KhbyIKmCJ6PTaDrcVD6:-Ki0CYUqUbdlLooZBZOu:b4jafdp) ([raw file](https://github.com/vaadin/maven-plugin/blob/11c53e90103828ae32627b688c5ee29c79d3660f/src/main/java/com/vaadin/integration/maven/UpdateFrontendMojo.java#L147)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

What if I _remove_ a dependency, is
</blockquote></details>

Ignore previous comment, please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/98)*

**Comment by elmot** [comment]
Bug:  I have multimodule project of structure:
```
test-root
 + web-component-dependency
 |     + src/main/resources/bower.json 
 + vaadin-ui
       + Dependency: web-component-dependency
```
"vaadin-ui" has update-frontend goal enabled

Expected behavior:
all the bower-related files are created in  test-root/vaadin-ui/src/blah-blah
Actual behavior:  
all the bower-related files are created in  test-root/src/blah-blah

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-:-KiHAtUJHSaaemgNlRo_:b-esr7d9)*

**Comment by Artur-** [comment]
Fixed

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-:-KiJEqs-_hkT_MRTWuv1:b-886gsx)*

**Comment by elmot** [comment]
Reviewed 1 of 12 files at r2, 1 of 2 files at r5.
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/resources/com/vaadin/integration/maven/move-build-to-webapp.js, line 1 at r5](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-KiT78OBorCBLP33gXsQ:-KiT78OBorCBLP33gXsR:b-80t6r8) ([raw file](https://github.com/vaadin/maven-plugin/blob/067a8a91d4e333ff61470cf1c1da2a5f4f60fcbd/src/main/resources/com/vaadin/integration/maven/move-build-to-webapp.js#L1)):*
> ```JavaScript
> // Move files from the "build" directory to the ../webapp/VAADIN/frontend/ dir 
> ```

what about `#!/usr/bin/env node` ?

---

*[src/main/resources/com/vaadin/integration/maven/update-addons-html.js, line 3 at r5](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-KiT5iblsNQwGOIuMmS_:-KiT5iblsNQwGOIuMmSa:bdrvs2a) ([raw file](https://github.com/vaadin/maven-plugin/blob/067a8a91d4e333ff61470cf1c1da2a5f4f60fcbd/src/main/resources/com/vaadin/integration/maven/update-addons-html.js#L3)):*
> autogenerated.html
bundle.html?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/98)*

**Comment by Artur-** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/resources/com/vaadin/integration/maven/move-build-to-webapp.js, line 1 at r5](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-KiT78OBorCBLP33gXsQ:-KiU2j2tBrErJQqQOq-n:b-896fix) ([raw file](https://github.com/vaadin/maven-plugin/blob/067a8a91d4e333ff61470cf1c1da2a5f4f60fcbd/src/main/resources/com/vaadin/integration/maven/move-build-to-webapp.js#L1)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

what about `#!/usr/bin/env node` ?
</blockquote></details>

Done.

---

*[src/main/resources/com/vaadin/integration/maven/update-addons-html.js, line 3 at r5](https://reviewable.io:443/reviews/vaadin/maven-plugin/98#-KiT5iblsNQwGOIuMmS_:-KiU3-iz7nHWTRN2ft90:b-896fix) ([raw file](https://github.com/vaadin/maven-plugin/blob/067a8a91d4e333ff61470cf1c1da2a5f4f60fcbd/src/main/resources/com/vaadin/integration/maven/update-addons-html.js#L3)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

> autogenerated.html
bundle.html?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/98)*

**Pull request closed without merging**
