### PR TITLE
Close files so a generated widget set can be deleted on Windows (#20478)

### LINKED ISSUE #74: AppWidgetset.gwt.xml is always generated and build for clean archetype-application
Originally by @johannesh2
Running:

```
mvn -B archetype:generate -DarchetypeGroupId=com.vaadin -DarchetypeArtifactId=vaadin-archetype-application -DarchetypeVersion=7.7.5 -DgroupId=org.test -DartifactId=vaadin-app -Dversion=1.0-SNAPSHOT
cd vaadin-app
mvn package
```

Compiles custom widgetset instead of using one int client jar.

### PR DESCRIPTION
**Pull request by Artur-**
Fixes #74

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/maven-plugin/77)

### CODE REVIEW

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java, line 121 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/77#-KXPdSA1E9hlaYNnQHv0:-KXPdSA2h-50p7GGn_Ze:b61ft5i) ([raw file](https://github.com/vaadin/maven-plugin/blob/64478ce56f0ddf77b1e502b04ff102efa9c60c1f/src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java#L121)):*
> ```Java
>                     OutputStream out = new FileOutputStream(appwsFile);
>                     IOUtil.copy(template, out);
>                     out.close();
> ```

Should be done in _finally_ block

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/77)*

**Comment by elmot** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java, line 130 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/77#-KXPdpeG-6Ek7778MIYY:-KXPdpeG-6Ek7778MIYZ:bcrraww) ([raw file](https://github.com/vaadin/maven-plugin/blob/64478ce56f0ddf77b1e502b04ff102efa9c60c1f/src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java#L130)):*
> ```Java
>                 FileInputStream fis = new FileInputStream(appwsFile);
>                 String generatedws = IOUtil.toString(fis);
>                 fis.close();
> ```

Must be done in _finally_ block

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/77)*

**Comment by Artur-** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java, line 121 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/77#-KXPdSA1E9hlaYNnQHv0:-KXPeachnr2wgOcpFX2C:bb7r2f0) ([raw file](https://github.com/vaadin/maven-plugin/blob/64478ce56f0ddf77b1e502b04ff102efa9c60c1f/src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java#L121)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> Should be done in _finally_ block
</details>
why?

---

*[src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java, line 130 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/77#-KXPdpeG-6Ek7778MIYY:-KXPebWvZSCy0lRYv0RW:bb7r2f0) ([raw file](https://github.com/vaadin/maven-plugin/blob/64478ce56f0ddf77b1e502b04ff102efa9c60c1f/src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java#L130)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary>
> Must be done in _finally_ block
</details>
why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/77)*

**Comment by elmot** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java, line 121 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/77#-KXPdSA1E9hlaYNnQHv0:-KXPrqafTU1-8jQvLFIz:bl2g05r) ([raw file](https://github.com/vaadin/maven-plugin/blob/64478ce56f0ddf77b1e502b04ff102efa9c60c1f/src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java#L121)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> why?
</details>
To be more or less sure it's really closed despite of any possible exceptions

---

*[src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java, line 130 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/77#-KXPdpeG-6Ek7778MIYY:-KXPs0g-xkm2a9dzAc1j:bl2g05r) ([raw file](https://github.com/vaadin/maven-plugin/blob/64478ce56f0ddf77b1e502b04ff102efa9c60c1f/src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java#L130)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> why?
</details>
To be more or less sure it's really closed despite of any possible exceptions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/77)*

**Comment by johannesh2** [comment]
Please merge this asap. Really annoying to have clean package always doing 47 seconds of widgetset compilation. I expected this to be fixed at least in 8 beta.

**Comment by Peppe** [comment]
Framework team, I also think this is very needed improvement that should be have a high priority. Takes me 1min 31s to run a project with all deps downloaded, on a powerful desktop PC. The first impressions are vital to users.

**Comment by tsuoanttila** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java, line 121 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/77#-KXPdSA1E9hlaYNnQHv0:-KZQTFz34hO9L4qqtyj3:bhdxgj6) ([raw file](https://github.com/vaadin/maven-plugin/blob/64478ce56f0ddf77b1e502b04ff102efa9c60c1f/src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java#L121)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

To be more or less sure it's really closed despite of any possible exceptions
</blockquote></details>

I will make the requested changes to make this patch progress.

---

*[src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java, line 130 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/77#-KXPdpeG-6Ek7778MIYY:-KZQTJaWZpqpxVR9czGg:bhdxgj6) ([raw file](https://github.com/vaadin/maven-plugin/blob/64478ce56f0ddf77b1e502b04ff102efa9c60c1f/src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java#L130)):*
<details><summary><i>Previously, elmot (Ilia Motornyi) wrote…</i></summary><blockquote>

To be more or less sure it's really closed despite of any possible exceptions
</blockquote></details>

I will make the requested changes to make this patch progress.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/77)*

**Comment by tsuoanttila** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java, line 121 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/77#-KXPdSA1E9hlaYNnQHv0:-KZQV8t1Oop8uH5cGU9E:b-xn41oh) ([raw file](https://github.com/vaadin/maven-plugin/blob/64478ce56f0ddf77b1e502b04ff102efa9c60c1f/src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java#L121)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I will make the requested changes to make this patch progress.
</blockquote></details>

Reviewable messed up commits. never mind.

---

*[src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java, line 130 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/77#-KXPdpeG-6Ek7778MIYY:-KZQVDVuRyA2x-i-1QJD:byr4ffv) ([raw file](https://github.com/vaadin/maven-plugin/blob/64478ce56f0ddf77b1e502b04ff102efa9c60c1f/src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java#L130)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

I will make the requested changes to make this patch progress.
</blockquote></details>

see above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/77)*

**Comment by tsuoanttila** [comment]
*[src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java, line 129 at r2](https://reviewable.io:443/reviews/vaadin/maven-plugin/77#-KZQYpxhi1UpuuxQHxip:-KZQYpxhi1UpuuxQHxiq:b273ui) ([raw file](https://github.com/vaadin/maven-plugin/blob/24ffd7371107cee3372080a5d7a3004ab2d75b50/src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java#L129)):*
> ```Java
>                 // not have sufficient API to only generate the widgetset when it is needed
>                 try (FileInputStream fis = new FileInputStream(appwsFile)) {
>                     String generatedws = IOUtil.toString(fis);
> ```

generatedws variable is used in the following if-block. Compilation error

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/77)*

**Comment by Artur-** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java, line 121 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/77#-KXPdSA1E9hlaYNnQHv0:-KZQyOxirQL1JrjJsWle:b-896fix) ([raw file](https://github.com/vaadin/maven-plugin/blob/64478ce56f0ddf77b1e502b04ff102efa9c60c1f/src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java#L121)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Reviewable messed up commits. never mind.
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java, line 130 at r1](https://reviewable.io:443/reviews/vaadin/maven-plugin/77#-KXPdpeG-6Ek7778MIYY:-KZQyQW7yf8qjxCD-TvR:b-896fix) ([raw file](https://github.com/vaadin/maven-plugin/blob/64478ce56f0ddf77b1e502b04ff102efa9c60c1f/src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java#L130)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java, line 129 at r2](https://reviewable.io:443/reviews/vaadin/maven-plugin/77#-KZQYpxhi1UpuuxQHxip:-KZQyPqKqiU0wo2TxsZY:b-896fix) ([raw file](https://github.com/vaadin/maven-plugin/blob/24ffd7371107cee3372080a5d7a3004ab2d75b50/src/main/java/com/vaadin/integration/maven/UpdateWidgetsetMojo.java#L129)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

generatedws variable is used in the following if-block. Compilation error
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/77)*

**Comment by elmot** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/77)*

**Comment by elmot** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/77#-:-KZRI6cf57QM2Pc7N9ap:bnfp4nl)*

**Comment by tsuoanttila** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-plugin/77)*

**Pull request merged**
